name = "nymph_lang"
version = "0.1.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
licences = ["MIT"]
repository = { type = "github", user = "theonlytails", repo = "nymph_lang" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
glint = ">= 1.0.1 and < 2.0.0"
chomp = ">= 0.1.0 and < 1.0.0"
envoy = ">= 1.0.1 and < 2.0.0"
file_stream = ">= 0.7.0 and < 1.0.0"
filepath = ">= 1.0.0 and < 2.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_fetch = ">= 1.0.1 and < 2.0.0"
gleam_httpc = ">= 2.2.0 and < 3.0.0"
gleam_json = ">= 1.0.1 and < 2.0.0"
dedent = ">= 1.0.0 and < 2.0.0"
gap = ">= 1.1.3 and < 2.0.0"
justin = ">= 1.0.1 and < 2.0.0"
hug = ">= 1.0.2 and < 2.0.0"
cactus = ">= 1.1.0 and < 2.0.0"
pprint = ">= 1.0.3 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

[javascript.deno]
allow_read = ["gleam.toml", "test", "build"]

[cactus.pre-commit]
actions = [{ command = "format", kind = "sub_command" }]
